/* =============================================
   PRODUCTS-DATA.JS — Kathy Designs
   Central product database for cross-page search.
   ============================================= */

const KATHY_ALL_PRODUCTS = [

  /* ---- WOMEN ---- */
  { id:'prod01', name:'Elegant Kente Dress',       price:250, image:'productImages/women1_1186.PNG',      category:'Women', page:'index.html' },
  { id:'prod02', name:'Ankara Wrap Dress',          price:280, image:'productImages/women2_1192.PNG',      category:'Women', page:'index.html' },
  { id:'prod03', name:'Kaba & Slit Set',            price:320, image:'productImages/women3_1193.PNG',      category:'Women', page:'index.html' },
  { id:'prod04', name:'African Print Jumpsuit',     price:290, image:'productImages/women4_1194.PNG',      category:'Women', page:'index.html' },
  { id:'prod05', name:'Batik Maxi Dress',           price:270, image:'productImages/women5_1471.PNG',      category:'Women', page:'index.html' },
  { id:'prod06', name:'Kente Midi Dress',           price:300, image:'productImages/women6_1473.PNG',      category:'Women', page:'index.html' },
  { id:'prod07', name:'Ankara Off-Shoulder',        price:260, image:'productImages/women7_1474.PNG',      category:'Women', page:'index.html' },
  { id:'prod08', name:'African Peplum Top',         price:180, image:'productImages/women8_1513.PNG',      category:'Women', page:'index.html' },
  { id:'prod09', name:'Dashiki Dress',              price:240, image:'productImages/women9_1514.PNG',      category:'Women', page:'index.html' },
  { id:'prod10', name:'Kente Two-Piece',            price:350, image:'productImages/women10_1515.PNG',     category:'Women', page:'index.html' },
  { id:'prod11', name:'Ankara Shirt Dress',         price:230, image:'productImages/women11_1523.PNG',     category:'Women', page:'index.html' },
  { id:'prod12', name:'African Bodycon Dress',      price:210, image:'productImages/women12_1521.PNG',     category:'Women', page:'index.html' },
  { id:'prod13', name:'Kente Evening Gown',         price:450, image:'productImages/women13_1394.PNG',     category:'Women', page:'index.html' },
  { id:'prod14', name:'Ankara Trouser Suit',        price:380, image:'productImages/women14_1516 (1).PNG', category:'Women', page:'index.html' },
  { id:'prod15', name:'Batik Skirt Set',            price:260, image:'productImages/women15_1522.PNG',     category:'Women', page:'index.html' },
  { id:'prod16', name:'African Print Blouse',       price:150, image:'productImages/women16.153.JPG',      category:'Women', page:'index.html' },
  { id:'prod17', name:'Kente Wrap Skirt',           price:190, image:'productImages/women17.png',          category:'Women', page:'index.html' },
  { id:'prod18', name:'Ankara Midi Skirt',          price:170, image:'productImages/womens18.png',         category:'Women', page:'index.html' },
  { id:'prod19', name:'GTP Print Dress',            price:220, image:'productImages/womens19.png',         category:'Women', page:'index.html' },
  { id:'prod20', name:'African Lace Dress',         price:390, image:'productImages/womens20.PNG',         category:'Women', page:'index.html' },
  { id:'prod21', name:'Kente Trouser Set',          price:340, image:'productImages/mens21.PNG',           category:'Women', page:'index.html' },
  { id:'prod22', name:'Ankara Bridal Gown',         price:550, image:'productImages/women22.PNG',          category:'Women', page:'index.html' },
  { id:'prod23', name:'Kente Cocktail Dress',       price:420, image:'productImages/women23.PNG',          category:'Women', page:'index.html' },
  { id:'prod24', name:'African Print Co-ord Set',   price:310, image:'productImages/women24.PNG',          category:'Women', page:'index.html' },

  /* ---- MEN ---- */
  { id:'mprod01', name:'Kente Agbada Set',          price:480, image:'productImages/menns.png',   category:'Men', page:'men.html' },
  { id:'mprod02', name:'Ankara Senator Suit',       price:420, image:'productImages/mens1.PNG',   category:'Men', page:'men.html' },
  { id:'mprod03', name:'Kente Smock Top',           price:280, image:'productImages/menss2.PNG',  category:'Men', page:'men.html' },
  { id:'mprod04', name:'African Print Shirt',       price:220, image:'productImages/mens3.PNG',   category:'Men', page:'men.html' },
  { id:'mprod05', name:'Ankara Jogger Set',         price:300, image:'productImages/mens5.PNG',   category:'Men', page:'men.html' },
  { id:'mprod06', name:'Dashiki Short Set',         price:310, image:'productImages/mens6.PNG',   category:'Men', page:'men.html' },
  { id:'mprod07', name:'Kente Trousers',            price:260, image:'productImages/mens7.PNG',   category:'Men', page:'men.html' },
  { id:'mprod08', name:'GTP Print Shirt',           price:190, image:'productImages/mens8.PNG',   category:'Men', page:'men.html' },
  { id:'mprod09', name:'Batik Kaftan',              price:350, image:'productImages/mens9.PNG',   category:'Men', page:'men.html' },
  { id:'mprod10', name:'Ankara Two-Piece',          price:380, image:'productImages/mens10.PNG',  category:'Men', page:'men.html' },
  { id:'mprod11', name:'Kente Polo Shirt',          price:210, image:'productImages/mens11.PNG',  category:'Men', page:'men.html' },
  { id:'mprod12', name:'African Linen Suit',        price:460, image:'productImages/mens12.PNG',  category:'Men', page:'men.html' },
  { id:'mprod13', name:'Kente Bowtie Set',          price:320, image:'productImages/mens13.PNG',  category:'Men', page:'men.html' },
  { id:'mprod14', name:'Ankara Blazer',             price:410, image:'productImages/mens14.PNG',  category:'Men', page:'men.html' },
  { id:'mprod15', name:'Senator Kaftan',            price:390, image:'productImages/mens15.PNG',  category:'Men', page:'men.html' },
  { id:'mprod16', name:"Cavali Gentleman's Belt",   price:180, image:'productImages/mens16.PNG',  category:'Men', page:'men.html' },
  { id:'mprod17', name:'Kente Print Shorts',        price:160, image:'productImages/mens17.PNG',  category:'Men', page:'men.html' },
  { id:'mprod18', name:'Ankara Casual Shirt',       price:200, image:'productImages/mens18.PNG',  category:'Men', page:'men.html' },
  { id:'mprod19', name:'African Embroidered Shirt', price:240, image:'productImages/mens19.PNG',  category:'Men', page:'men.html' },
  { id:'mprod20', name:'Kente Waistcoat',           price:270, image:'productImages/mens20.PNG',  category:'Men', page:'men.html' },
  { id:'mprod21', name:'Kente Trouser Set',         price:340, image:'productImages/mens21.PNG',  category:'Men', page:'men.html' },
  { id:'mprod22', name:'Ankara Grand Boubou',       price:500, image:'productImages/mens22.PNG',  category:'Men', page:'men.html' },
  { id:'mprod23', name:'Kente Dashiki Set',         price:360, image:'productImages/mens23.PNG',  category:'Men', page:'men.html' },
  { id:'mprod24', name:'African Print Kaftan',      price:290, image:'productImages/mens24.PNG',  category:'Men', page:'men.html' },

  
 

  /* ---- BAGS & SHOES ---- */
  { id:'bsprod01', name:'Designer Tote Bag',        price:320, image:'productImages/WomensBAG1.PNG',       category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod02', name:'Leather Shoulder Bag',     price:290, image:'productImages/WomensBAG2.PNG',       category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod03', name:'Ankara Print Bag',         price:270, image:'productImages/WomensBAG3.PNG',       category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod04', name:'Luxury Handbag',           price:380, image:'productImages/bags4.PNG',            category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod05', name:'Croc Print Bag',           price:310, image:'productImages/bags5.PNG',            category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod06', name:'Mini Crossbody Bag',       price:220, image:'productImages/bags6.PNG',            category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod07', name:'Evening Clutch',           price:180, image:'productImages/bags7.PNG',            category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod08', name:'Woven Basket Bag',         price:200, image:'productImages/bags8.PNG',            category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod09', name:'Suede Bucket Bag',         price:260, image:'productImages/bags9.PNG',            category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod10', name:'Kente Clutch Bag',         price:250, image:'productImages/bags10.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod11', name:'Chain Strap Bag',          price:230, image:'productImages/bags11.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod12', name:'Leopard Print Bag',        price:270, image:'productImages/bags12.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod13', name:'Structured Work Bag',      price:350, image:'productImages/bags13.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod14', name:'Fendi Style Bag',          price:420, image:'productImages/bags14.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod15', name:'Quilted Flap Bag',         price:300, image:'productImages/bags15.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod16', name:'Satchel Bag',              price:280, image:'productImages/bags16.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod17', name:'Envelope Clutch',          price:160, image:'productImages/bags17.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod18', name:'Metallic Evening Bag',     price:240, image:'productImages/bags18.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod19', name:'Brown Laced Shoes',        price:280, image:'productImages/brownLaced-shoes.jpg', category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod20', name:'Clark Comfort Shoes',      price:290, image:'productImages/clark-shoes.jpg',      category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod21', name:'Brown Leather Bag',        price:310, image:'productImages/Brown-Bag.JPG',        category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod22', name:'Ankara Tote Bag',          price:240, image:'productImages/bags19.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod23', name:'Platform Heels',           price:330, image:'productImages/bags20.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },
  { id:'bsprod24', name:'Croc Stiletto Heels',      price:360, image:'productImages/bags21.PNG',           category:'Bags & Shoes', page:'bags-shoes.html' },

  /* ---- FABRICS ---- */
  { id:'fprod01', name:'Ankara Wax Print',          price:85,  image:'productImages/fabric1.png',   category:'Fabrics', page:'fabrics.html' },
  { id:'fprod02', name:'GTP Holland Print',         price:95,  image:'productImages/fabric2.png',   category:'Fabrics', page:'fabrics.html' },
  { id:'fprod03', name:'Batik African Print',       price:75,  image:'productImages/fabric3.png',   category:'Fabrics', page:'fabrics.html' },
  { id:'fprod04', name:'Kente Strip Fabric',        price:150, image:'productImages/fabrics4.png',  category:'Fabrics', page:'fabrics.html' },
  { id:'fprod05', name:'Ankara Floral Print',       price:80,  image:'productImages/fabric5.png',   category:'Fabrics', page:'fabrics.html' },
  { id:'fprod06', name:'Adinkra Print Fabric',      price:100, image:'productImages/fabrics6.png',  category:'Fabrics', page:'fabrics.html' },
  { id:'fprod07', name:'GTP Wax Print',             price:95,  image:'productImages/fabrics7.png',  category:'Fabrics', page:'fabrics.html' },
  { id:'fprod08', name:'African Tie-Dye Fabric',    price:70,  image:'productImages/fabrics8.png',  category:'Fabrics', page:'fabrics.html' },
  { id:'fprod09', name:'Dashiki Print Fabric',      price:85,  image:'productImages/fabrics9.png',  category:'Fabrics', page:'fabrics.html' },
  { id:'fprod10', name:'Mudcloth Fabric',           price:110, image:'productImages/fabrics10.png', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod11', name:'Kente Weave Fabric',        price:140, image:'productImages/fabrics11.png', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod12', name:'Ankara Abstract Print',     price:88,  image:'productImages/fabrics12.png', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod13', name:'Kente Silk Blend',          price:180, image:'productImages/fabrics13.png', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod14', name:'African Geometric Print',   price:90,  image:'productImages/fabrics14.png', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod15', name:'GTP Super Wax',             price:105, image:'productImages/fabrics15.png', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod16', name:'Kente Cotton Blend',        price:130, image:'productImages/fabric16.png',  category:'Fabrics', page:'fabrics.html' },
  { id:'fprod17', name:'Smock Northern Fabric',     price:115, image:'productImages/fabrics17.JPG', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod18', name:'African Lace Fabric',       price:120, image:'productImages/fabrics18.PNG', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod19', name:'Ankara Bold Print',         price:85,  image:'productImages/fabrics19.PNG', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod20', name:'Kente Festival Fabric',     price:160, image:'productImages/fabrics20.PNG', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod21', name:'Smock Embroidered Fabric',  price:125, image:'productImages/fabrics21.PNG', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod22', name:'Ankara Royal Print',        price:92,  image:'productImages/fabrics22.PNG', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod23', name:'GTP Exclusive Print',       price:115, image:'productImages/fabrics23.PNG', category:'Fabrics', page:'fabrics.html' },
  { id:'fprod24', name:'Kente Premium Weave',       price:170, image:'productImages/fabrics24.PNG', category:'Fabrics', page:'fabrics.html' },

  /* ---- ACCESSORIES ---- */
  { id:'aprod01', name:'Beaded Necklace',           price:85,  image:'productImages/access1.PNG',           category:'Accessories', page:'accessories.html' },
  { id:'aprod02', name:'African Bracelet',          price:65,  image:'productImages/access2.PNG',           category:'Accessories', page:'accessories.html' },
  { id:'aprod03', name:'Kente Headwrap',            price:75,  image:'productImages/access3.PNG',           category:'Accessories', page:'accessories.html' },
  { id:'aprod04', name:'Waist Beads',               price:55,  image:'productImages/access4.PNG',           category:'Accessories', page:'accessories.html' },
  { id:'aprod05', name:'Gold Drop Earrings',        price:95,  image:'productImages/access5.png',           category:'Accessories', page:'accessories.html' },
  { id:'aprod06', name:'Ankara Headband',           price:45,  image:'productImages/access6.png',           category:'Accessories', page:'accessories.html' },
  { id:'aprod07', name:'Kente Bow Tie',             price:70,  image:'productImages/access7.png',           category:'Accessories', page:'accessories.html' },
  { id:'aprod08', name:'African Print Scarf',       price:60,  image:'productImages/access8.png',           category:'Accessories', page:'accessories.html' },
  { id:'aprod09', name:'Shiny Gold Heels',          price:280, image:'productImages/shinyGold-shoe.jpg',    category:'Accessories', page:'accessories.html' },
  { id:'aprod10', name:'Pink Stiletto Heels',       price:260, image:'productImages/pink-heels.jpg',        category:'Accessories', page:'accessories.html' },
  { id:'aprod11', name:'Leopard Print Bag',         price:270, image:'productImages/leopard-bag.jpg',       category:'Accessories', page:'accessories.html' },
  { id:'aprod12', name:'Ferragamo Style Heels',     price:350, image:'productImages/Faragamo-shoes.jpg',    category:'Accessories', page:'accessories.html' },
  { id:'aprod13', name:'Fendi Black Heels',         price:420, image:'productImages/Fendi-black.jpg',       category:'Accessories', page:'accessories.html' },
  { id:'aprod14', name:'DKNY Stilettos',            price:380, image:'productImages/dkny-shoe.jpg',         category:'Accessories', page:'accessories.html' },
  { id:'aprod15', name:'Cowgirl Ankle Boots',       price:310, image:'productImages/cowgirl-shoe.jpg',      category:'Accessories', page:'accessories.html' },
  { id:'aprod16', name:'Classy Brown Heels',        price:290, image:'productImages/classyBrown-shoes.jpg', category:'Accessories', page:'accessories.html' },
  { id:'aprod17', name:'Butterfly Heels',           price:275, image:'productImages/Butterfly-shoe.jpg',    category:'Accessories', page:'accessories.html' },
  { id:'aprod18', name:'Butteri Leather Shoes',     price:320, image:'productImages/butteri-shoes.jpg',     category:'Accessories', page:'accessories.html' },
  { id:'aprod19', name:'Brown Laced Shoes',         price:280, image:'productImages/brownLaced-shoes.jpg',  category:'Accessories', page:'accessories.html' },
  { id:'aprod20', name:'Clark Comfort Shoes',       price:290, image:'productImages/clark-shoes.jpg',       category:'Accessories', page:'accessories.html' },
  { id:'aprod21', name:'Brown Leather Bag',         price:310, image:'productImages/Brown-Bag.JPG',         category:'Accessories', page:'accessories.html' },
  { id:'aprod22', name:'Ankara Waist Belt',         price:80,  image:'productImages/access9.PNG',           category:'Accessories', page:'accessories.html' },
  { id:'aprod23', name:'Beaded Anklet Set',         price:50,  image:'productImages/access10.PNG',          category:'Accessories', page:'accessories.html' },
  { id:'aprod24', name:'African Print Hair Tie',    price:35,  image:'productImages/access11.PNG',          category:'Accessories', page:'accessories.html' },

];